# Generated by Django 3.1.5 on 2021-02-09 00:34

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Kaтегория')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Слаг')),
                ('record_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('body', models.TextField(verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('online_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=15)),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('flag', models.CharField(choices=[('ru', 'ru'), ('us', 'us'), ('eu', 'eu'), ('ua', 'ua')], default='ru', max_length=15, verbose_name='Флаг')),
                ('added_to_cat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Добавлен')),
                ('meta_desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='records.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('body', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('author', models.CharField(default='Аноним', max_length=80, verbose_name='Автор комментария')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-updated'],
            },
        ),
    ]
