# Generated by Django 3.1.5 on 2021-02-15 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ответа сервера')),
                ('response', models.CharField(max_length=500, verbose_name='Ответ сервера')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
            ],
            options={
                'verbose_name': 'Ответ сервера',
                'verbose_name_plural': 'Ответы от сервера',
                'ordering': ['-created'],
            },
        ),
    ]
