# Generated by Django 3.1.5 on 2021-02-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordhistory', to='records.record'),
        ),
    ]
